services:
  db:
    image: postgres:16.3
    container_name: psocial
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: peterharvard210
      POSTGRES_DB: psocial
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    container_name: redis
    ports:
      - "6380:6379"
    command: redis-server --save 60 1 --loglevel warning

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis
    ports:
      - "127.0.0.1:8081:8081"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  db-data:
